# Generated by Django 4.0.1 on 2022-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peid', models.CharField(max_length=50)),
                ('pfname', models.CharField(max_length=30)),
                ('plname', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('profession', models.CharField(max_length=20)),
            ],
        ),
    ]
