# Generated by Django 4.0.1 on 2022-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='id',
        ),
        migrations.AlterField(
            model_name='professional',
            name='peid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='plname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
