# Generated by Django 4.0.2 on 2022-04-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
