# Generated by Django 4.0.1 on 2022-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_professional_id_alter_professional_peid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
