# Generated by Django 4.0.1 on 2022-02-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_professional_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LegalSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopicname', models.CharField(max_length=50)),
                ('subtopicimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('legaltopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.legalright')),
            ],
        ),
    ]
