# Generated by Django 4.0.1 on 2022-02-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_legalright_legalsubtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=200)),
                ('lawsubtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.legalsubtopic')),
            ],
        ),
    ]
