# Generated by Django 4.0.2 on 2022-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychoDisorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdname', models.CharField(max_length=50)),
            ],
        ),
    ]
