# Generated by Django 4.0.1 on 2022-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_lawfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsubtopic',
            name='subtopicimage',
            field=models.ImageField(blank=True, default='static/images/burger-1.jpg', null=True, upload_to=''),
        ),
    ]
