# Generated by Django 4.0.1 on 2022-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_legalsubtopic_subtopicimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsubtopic',
            name='subtopicimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
