# Generated by Django 4.0.1 on 2022-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_legalsubtopic_subtopicimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
