# Generated by Django 4.0.2 on 2022-04-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_customer_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
